# Generated by Django 4.2 on 2024-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstoproduct',
            name='paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Оплачено'),
        ),
    ]
