# Generated by Django 4.2 on 2024-04-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_studentstoproduct_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstoproduct',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
